# Generated by Django 4.0.2 on 2022-02-09 19:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название статьи')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(max_length=200, verbose_name='текст')),
                ('photo', models.ImageField(upload_to='post_images', verbose_name='выбрать фото')),
            ],
        ),
    ]
