# Generated by Django 4.0.2 on 2022-02-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_news_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutcomp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Корхонамиз хакида')),
                ('title_ru', models.CharField(max_length=30, null=True, verbose_name='Корхонамиз хакида')),
                ('title_uz', models.CharField(max_length=30, null=True, verbose_name='Корхонамиз хакида')),
                ('text', models.CharField(max_length=300, verbose_name='Текст')),
                ('text_ru', models.CharField(max_length=300, null=True, verbose_name='Текст')),
                ('text_uz', models.CharField(max_length=300, null=True, verbose_name='Текст')),
                ('photo', models.ImageField(upload_to='post_images', verbose_name='Фото о нашей компании')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информации',
            },
        ),
    ]
