# Generated by Django 4.0.2 on 2022-02-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_articles_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('text', models.CharField(max_length=300, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Коментарие',
                'verbose_name_plural': 'Коментарии',
            },
        ),
    ]
