# Generated by Django 4.0.2 on 2022-02-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
    ]
